version: "3.8"

services:
  sporttery-chrome:
    image: chromedp/headless-shell:latest
    container_name: sporttery-chrome
    # 使用镜像自带的启动脚本：内部 9223 + socat 转发到 9222
    # 不要覆写 command，避免端口/参数冲突
    ports:
      - "9222:9222"
    shm_size: "1gb"
    networks:
      sporttery-net:
        aliases:
          - chrome    # 供代码内使用的主机名（ws://chrome:9222/…）
    restart: unless-stopped

  sporttery-streamer:
    build: .
    image: sporttery-streamer:latest
    container_name: sporttery-streamer
    env_file:
      - .env
    environment:
      # 通过 9222 发现 DevTools（容器间可达）
      CHROME_DISCOVERY: "http://sporttery-chrome:9222/json/version"
    depends_on:
      - sporttery-chrome
    networks:
      - sporttery-net
    restart: unless-stopped

networks:
  sporttery-net:
    driver: bridge
