version: "3.8"

services:
  chrome:
    image: chromedp/headless-shell:latest
    container_name: sporttery-chrome
    command:
      - --no-sandbox
      - --use-gl=angle
      - --use-angle=swiftshader
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9223
      - --disable-web-security
      - --user-data-dir=/tmp/headless-shell
    ports:
      - "9222:9222"
    networks:
      - sporttery-net
    restart: unless-stopped

  sporttery-streamer:
    build: .
    image: sporttery-streamer:latest
    container_name: sporttery-streamer
    env_file:
      - .env
    depends_on:
      - chrome
    networks:
      - sporttery-net
    restart: unless-stopped

networks:
  sporttery-net:
    driver: bridge
